%%%%evaluate_linking.m%%%%
% [stats,auto_stats]=evaluate_linking(param,manual_indiv,auto_locations,auto_ctimes,run_options,stations)
%    Compare manual detections with automated, in terms of detection times
%    at stations.
%    Input:
%           run_options.strict_eval_tolerance:  If one, manual and auto detections must
%               overlap 50% in time AND frequency.  If two, compare manual
%               and auto detections via time tolerances only, with no overlap
%               requirement.  If three, try to match
%               by location...
%           run_options.match_tol:  fractional overlap required for a match.  e.g. 0.25 means 25% ovlap in time
%           manual_indiv{1}: set of arrays containing individual manual detection
%           auto_locations:  Locations generated by automated
%           auto_ctimes:  matrix of individual detections on each DASAR, for convenience
%           stations: ?
%   Output: 
%       stats:  structure, with all fields (except one) same length as number of manual detections:
%           Ncompare_matches: The number of time/frequency matches from a manual linkage
%               that are present in
%               any auto linkage.  Anwsers whether a given manual
%               station detection  has been linked into any compare station
%               detection. 
%           Nstation_match: if stations exist: The number of manual detection present in a
%               station.  Answers whether any detections were available for
%               linking.
%           Nstations_index_match:  if stations exist: a {Nmanual}{Ndasr} cell array that contains
%               indicies of stations that match given manual call at that
%               DASAR, thus determining whether automated detections were
%               available to link.
%           Nsplit_links: The number of compare locations that contain
%               portions of a given manual location.  Should be one,
%               anything higher indicates a linkage problem.  Different
%               than Ncompare_matches in that the former counts total
%               detections matching the bsase, while Nsplit_links lists
%               the number of compare links that have contributed these
%               detections.
%           Ilocs_best_match:  The index of the automated location that
%               contains the largest number of matches with a given
%               manual result.
%           Nlongest_link: The maximum number of automated detections present
%               in the manual location given by 'Ilocs_best_match'
%
%           match_flag:  Contains '1' if associated manual detection is
%               matched, otherwise zero
%
%      auto_stats:  Same as status but with manual and automated swapped


function [stats,auto_stats]=evaluate_linking(param,manual_indiv,auto_locations,auto_ctimes,run_options,stations)

if ~exist('stations')
    stations=[];
end

%Information for third evaluation option--what should range and time
%tolerance be?
%DdB=A*log10(1+dr/R), or dr=R*DdB/A
dr2=(10000*2/15).^2;
%bufferTol=3;
bufferTol=run_options.eval_tol;

Idebug=0;  %Plot debug information...

if isempty(manual_indiv.ctime)|isempty(auto_ctimes)
    stats=[];
    auto_stats=[];
    disp('empty data')
    return
end


first_time=manual_indiv.ctime(1,manual_indiv.ctime(1,:)>0);  %First manual detection

if ~isfield(param.energy,'nsamples')||param.energy.nsamples==0,
    max_ctime=Inf;
else
    max_ctime=min(first_time)+param.energy.nsamples/param.Fs;
end

fprintf('evaluate_linking: max_ctime is %s\n',ctime2str(max_ctime));

%%Determine dimensions of structures
Nauto=size(auto_ctimes,1);
Nstations=length(auto_locations{1}.ctime_min);
if size(manual_indiv.ctime,2)~=Nstations
    disp('manual and auto dasar numbers don''t match');
    
end

%Unpack automated detections into a structure identical to manual results...
auto_indiv.duration=zeros(Nauto,Nstations);
auto_indiv.flo=zeros(Nauto,Nstations);
auto_indiv.fhi=zeros(Nauto,Nstations);
auto_indiv.ctime=auto_ctimes;
auto_success_ctime=zeros(Nauto,1); %Time call generated
auto_loc=zeros(Nauto,2);  %%UTM location

for I=1:Nauto
    auto_indiv.duration(I,:)=auto_locations{I}.Totalduration';
    auto_indiv.flo(I,:)=auto_locations{I}.Totalfmin';
    auto_indiv.fhi(I,:)=auto_locations{I}.Totalfmax';
    if isfield(auto_locations{I}.position,'ctime')
        auto_success_ctime(I)=auto_locations{I}.position.ctime;
        auto_loc(I,:)=auto_locations{I}.position.location;
    else
        %disp('Warning!! Unsuccesful localizations present in data');
    end
end




%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%For every manual detection...%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%find_corresponding_matches(base_indiv,compare_indiv,run_options,bufferTol,max_ctime)
stats=find_corresponding_matches(manual_indiv,auto_indiv,run_options,bufferTol,0,max_ctime,stations);

    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%For every automated detection compute similar stats%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

disp('evaluate_linking:  computing auto detection stats...');

auto_stats=find_corresponding_matches(auto_indiv,manual_indiv,run_options,bufferTol,0,max_ctime,stations);


   
end
